### ISSUE TITLE
Main Menu Doesn't work Correctly With Bigger GUI

### ISSUE THREAD

**Issue by EddieFromMc** [ShadowRaptorMC/galacticdrive#18]
## Bug description
When Scaling GUI to bigger sizes, parts of the menu become cut off

## Did this behavior work in a previous version?
From my few minutes in 1.0 It was working fine

## Steps to reproduce
Change GUI Scale in Video Settings to other than 'Auto'

## Logs
* Client/Server Log:N/A
* Crash Log:N/A

## Client information
* Modpack Version:0.2 Alpha
* Java Version: Azulu Zulu JDK 17.30.15 (17.0.1), 64-bit
* Launcher Used:MultiMC
* Memory Allocated:~10,000mb
* Singleplayer/Server:N/A
* Server API:N/A

**Comment by zediious** [comment]
This may be related to the bounding box of the some of the elements I have in the main menu, but I am not 100% certain just looking. This will be delved into.

**Comment by zediious** [comment]
This has been fixed with the addition of the "Main Menu Scale" mod

[https://github.com/ShadowRaptorMC/galacticdrive/pull/14/commits/c1bcb253cf9ba7fe1c6d690e570307b849112cfc](https://github.com/ShadowRaptorMC/galacticdrive/pull/14/commits/c1bcb253cf9ba7fe1c6d690e570307b849112cfc)

**Comment by zediious** [comment]
Fix present in new release

[https://github.com/ShadowRaptorMC/galacticdrive/releases/tag/0.2.4](https://github.com/ShadowRaptorMC/galacticdrive/releases/tag/0.2.4)
